const express = require('express');
const authRoutes = require('./auth.routes');
const studentRoutes = require('./student.routes');
const staffRoutes = require('./staff.routes');
const academicYearRoutes = require('./academicYear.routes');
const classRoutes = require('./class.routes');
const sectionRoutes = require('./section.routes');
const subjectRoutes = require('./subject.routes');
const enrollmentRoutes = require('./enrollment.routes');
const teacherAssignmentRoutes = require('./teacherAssignment.routes');
const attendanceRoutes = require('./attendance.routes');
const timetableRoutes = require('./timetable.routes');
const examRoutes = require('./exam.routes');
const examScheduleRoutes = require('./examSchedule.routes');
const resultRoutes = require('./result.routes');
const leaveRoutes = require('./leave.routes');
const odRoutes = require('./od.routes');
const announcementRoutes = require('./announcement.routes');
const notificationRoutes = require('./notification.routes');
const reportRoutes = require('./report.routes');
const promotionRoutes = require('./promotion.routes');
const activityLogRoutes = require('./activityLog.routes');
const backupRoutes = require('./backup.routes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/students', studentRoutes);
router.use('/staff', staffRoutes);
router.use('/academic-years', academicYearRoutes);
router.use('/classes', classRoutes);
router.use('/sections', sectionRoutes);
router.use('/subjects', subjectRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/teacher-assignments', teacherAssignmentRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/timetable', timetableRoutes);
router.use('/exams', examRoutes);
router.use('/exam-schedules', examScheduleRoutes);
router.use('/results', resultRoutes);
router.use('/leaves', leaveRoutes);
router.use('/od-requests', odRoutes);
router.use('/announcements', announcementRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reports', reportRoutes);
router.use('/promotions', promotionRoutes);
router.use('/activity-logs', activityLogRoutes);
router.use('/backups', backupRoutes);

module.exports = router;
